export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_FITNESS_PRODUCTS = "FETCH_FITNESS_PRODUCTS";
export const FETCH_TENNIS_PRODUCTS = "FETCH_TENNIS_PRODUCTS";
export const FETCH_OTHERS_PRODUCTS = "FETCH_OTHERS_PRODUCTS";
