export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_FITNESS_PRODUCTS = "FETCH_FITNESS_PRODUCTS";
export const FETCH_HIKING_PRODUCTS = "FETCH_HIKING_PRODUCTS";
export const FETCH_SWIMMING_PRODUCTS = "FETCH_SWIMMING_PRODUCTS";
